name: 'Hello World'

description: 'A simple data validator using REGEX'

inputs:
  regex:
    description: 'The regex that we are going to use to match the #data-to-validate'
    required: true

  data-to-validate:
    description: 'The data that you want to validate'
    required: true

outputs:
  time: # id of output
    description: 'The time we greeted you'
    
runs:
  using: 'node20'
  main: 'index.js'