name: Must Fail

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Must Fail

    steps:
      - name: Test 1 
        continue-on-error: true
        uses: hrossi/hello-world-javascript-action@v1.4
        with:
          regex: "^\\d+$"
          data-to-validate: "ABC 123"

      - name: Test 2
        continue-on-error: true
        uses: hrossi/hello-world-javascript-action@v1.4
        with:
          regex: "^[0-9]{4}$"
          data-to-validate: "ABC 123"

      - name: Test 3
        continue-on-error: true
        uses: hrossi/hello-world-javascript-action@v1.4
        with:
          regex: "^[0-9]{4}$"
          data-to-validate: "12345"

      - name: Checar Status
        run: |
          if [ ${{ job.status }} == 'failure' ]; then
            echo "Todos os steps falharam, considerado um SUCESSO"
            exit 0
          else
            echo "Algum step foi bem-sucedido, considerado um FRACASSO"
            exit 1
          fi