name: Tests

on: 
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Tests

    steps:
      - name: Should PASS
        uses: hrossi/hello-world-javascript-action@v1.4
        with:
          regex: "\\d"
          data-to-validate: "123"